package com.ocr.jpeg2pdf;

import com.ocr.jpeg2pdf.model.OcrResult;
import com.ocr.jpeg2pdf.service.OfdPostProcessService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class TestOfdPostProcess implements CommandLineRunner {
    
    private final OfdPostProcessService ofdPostProcessService;
    
    public TestOfdPostProcess(OfdPostProcessService ofdPostProcessService) {
        this.ofdPostProcessService = ofdPostProcessService;
    }
    
    public static void main(String[] args) {
        SpringApplication.run(TestOfdPostProcess.class, args);
    }
    
    @Override
    public void run(String... args) throws Exception {
        System.out.println("Testing OFD post-processing...");
        
        // Input OFD (generated by ofdrw-converter)
        Path inputOfd = Paths.get("P:/OCR/Output/input.ofd");
        
        // Output OFD (with text layer)
        Path outputOfd = Paths.get("P:/OCR/Output/output_with_text.ofd");
        
        // Create sample OCR result
        OcrResult ocrResult = new OcrResult();
        List<OcrResult.TextPosition> positions = new ArrayList<>();
        
        OcrResult.TextPosition pos1 = new OcrResult.TextPosition();
        pos1.setText("Test Text 1");
        pos1.setX(100.0);
        pos1.setY(100.0);
        pos1.setWidth(200.0);
        pos1.setHeight(50.0);
        pos1.setFontSize(24.0f);
        positions.add(pos1);
        
        ocrResult.setTextPositions(positions);
        
        List<OcrResult> ocrResults = new ArrayList<>();
        ocrResults.add(ocrResult);
        
        // Process OFD
        ofdPostProcessService.addTextLayerToOfd(inputOfd, ocrResults, outputOfd);
        
        System.out.println("Test complete!");
        System.out.println("Output: " + outputOfd);
    }
}
